BYGsite/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
   path('', include('staticpages.urls')),
   path('destinos/', include('destinos.urls')),
    path('admin/', admin.site.urls),
]

destinos/urls.py
from django.urls import path

from . import views

app_name = 'destinos'
urlpatterns = [
    path('', views.DestinoListView.as_view(), name='index'), 
    path('search/', views.search_destinos, name='search'),
    path('create/', views.create_destino, name='create'),
    path('<int:pk>/', views.DestinoDetailView.as_view(), name='detail'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
     path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

destinos/models.py
from django.db import models
from django.conf import settings

class Empresa(models.Model):
    CNPJ = models.CharField(max_length=255)
    nomeFantasia = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.nomeFantasia}'

class Destino(models.Model):
    name = models.CharField(max_length=255)
    categoria = models.CharField(max_length=255)
    destino_url = models.URLField(max_length=200, null=True)
    descricao = models.CharField(max_length=1000)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    likes = models.IntegerField()

    def __str__(self):
        return f'{self.name} - {self.likes}'

staticpages/models.py
from django.db import models

# Create your models here.

destinos/forms.py
from django.forms import ModelForm
from .models import Destino

class DestinoForm(ModelForm):
    class Meta:
        model = Destino
        fields = [
            'name',
            'categoria',
            'descricao',
            'destino_url',
        ]

destinos/views.py
from django.http import HttpResponse,HttpResponseRedirect
from .temp_data import destino_data
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from .models import Destino
from django.views import generic
from .forms import DestinoForm


class DestinoDetailView(generic.DetailView):
    model = Destino
    template_name = 'destinos/detail.html'

class DestinoListView(generic.ListView):
    model = Destino
    template_name = 'destinos/index.html'

def search_destinos(request):
    context = {}
    if request.GET.get('query', False):
        context = {
            "destino_list": [
                m for m in destino_data
                if request.GET['query'].lower() in m['name'].lower()
            ]
        }
    return render(request, 'destinos/search.html', context) 

def create_destino(request):
    if request.method == 'POST':
        form = DestinoForm(request.POST)
        if form.is_valid():
            destino_name = form.cleaned_data['name']
            destino_categoria = form.cleaned_data['categoria']
            destino_descricao = form.cleaned_data['descricao']
            destino_url = form.cleaned_data['destino_url']
            destino = Destino(name=destino_name,
                          categoria=destino_categoria,
                          descricao=destino_descricao,
                          destino_url=destino_url)
            destino.save()
            return HttpResponseRedirect(
                reverse('destinos:detail', args=(destino.id, )))
    else:
        form = DestinoForm()
    context = {'form': form}
    return render(request, 'destinos/create.html', context)

staticpages/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

destinos/templates/destinos/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Destino</h2>
<form method="post" action="{% url 'destinos:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

destinos/templates/destinos/detail.html
{% extends 'base.html' %} {% block title %} {{ destino.name }} ({{
    destino.categoria }} {% endblock title %} {% block content %}
    <h2>{{ destino.name }}</h2>
    
    <section class="descricao-do-destino">
      <img src="{{ destino.destino_url }}" alt="Paisagem de {{ destino.name}}" />
      <ul>
        <li>Nome: {{ destino.name}}
        <li>Categoria: {{ destino.categoria}}</li>
        <li>Descrição: {{destino.descricao}}
      </ul>
    </section>
    
    {% endblock content %}

destinos/templates/destinos/index.html
{% extends 'base.html' %} {% block content %}
<h2>Todos os Filmes</h2>
<section>
  <p>
    Muitos resultados? <a href="{% url 'destinos:search' %}">Buscar Destinos</a>
  </p>
  <p>
    Não encontrou o destino?
    <a href="{% url 'destinos:create' %}">Adicionar Novo Destino</a>
  </p>
</section>
{% if destino_list %}
<section class="lista-de-cards">
  {% for destino in destino_list %}
  <article class="card">
    <a href="{% url 'destinos:detail' destino.id %}"
      ><img src="{{ destino.destino_url}}" alt="Paisagem de{{destino.name}}"
    /></a>
    <p>{{ destino.name }} ({{ destino.categoria }})</p>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum destino.</p>
{% endif %} {% endblock content %}

destinos/templates/destinos/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if destino_list %}
<section class="lista-de-cards">
    {% for destino in destino_list %}
    <article class="card">
        <img src="{{ destino.destino_url }}" alt="Paisagem de{{ destino.name}}">
        <p>{{ destino.name }} ({{ destino.categoria }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum destino para a busca.</p>
{% endif %}

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre a BYG</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Viaje com a BYG</i></h1>
<p>A Página para quem viaja de verdade</p>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} |Be Your Guide!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> 
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'destinos:index' %}">Destinos</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023</small>
        </p>
    </footer>
</body>

</html>